import assert from 'node:assert/strict';
import { _electron as electron,chromium } from 'playwright-core';
import { mkdir,mkdtemp,readFile,writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join,resolve } from 'node:path';
import { randomBytes } from 'node:crypto';
import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
import { setTimeout as delay } from 'node:timers/promises';
import { createMockClassroom } from './mock-classroom.mjs';
const mock=await createMockClassroom(),data=await mkdtemp(join(tmpdir(),'attendance-scheduler-ui-'));
const defaultApp=process.platform==='win32'?'release-public/win-unpacked/Attendance Handler.exe':'release/mac-arm64/Attendance Handler.app/Contents/MacOS/Attendance Handler';
const executablePath=resolve(process.env.ATTENDANCE_TEST_APP||defaultApp),key=randomBytes(32).toString('hex'),synthetic=process.env.ATTENDANCE_UI_CIPHER==='synthetic';
const exec=promisify(execFile),native=async(...args)=>JSON.parse((await exec(resolve(`dist-electron/attendance-native${process.platform==='win32'?'.exe':''}`),args,{windowsHide:true})).stdout);
let application,window,pid,launcher,classroom;
const checks=[],errors=[],chromePids=[];
const alive=id=>{try{process.kill(id,0);return true;}catch{return false;}};
async function boot(target){application=await electron.launch({executablePath,env:{...process.env,ATTENDANCE_DEMO:'1',ATTENDANCE_ORIGIN:mock.origin,ATTENDANCE_DATA_DIR:data}});pid=await application.evaluate(()=>process.pid);launcher=application.process();window=await application.firstWindow();window.on('pageerror',error=>errors.push(error.message));
 await application.evaluate(({safeStorage},{hex,synthetic,target})=>{
  const original=Date.now.bind(Date);let offset=target?target-original():0;Date.now=()=>original()+offset;globalThis.__advanceScheduleTo=value=>{offset=value-original();};
  if(synthetic){const {randomBytes,createCipheriv,createDecipheriv}=process.getBuiltinModule('node:crypto'),key=Buffer.from(hex,'hex');safeStorage.isEncryptionAvailable=()=>true;safeStorage.encryptString=text=>{const iv=randomBytes(12),c=createCipheriv('aes-256-gcm',key,iv);return Buffer.concat([iv,c.update(text,'utf8'),c.final(),c.getAuthTag()]);};safeStorage.decryptString=bytes=>{const c=createDecipheriv('aes-256-gcm',key,bytes.subarray(0,12));c.setAuthTag(bytes.subarray(-16));return Buffer.concat([c.update(bytes.subarray(12,-16)),c.final()]).toString();};}
 },{hex:key,synthetic,target});await window.getByRole('heading',{name:'我的课程',exact:true}).waitFor();await application.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].setBounds({width:900,height:640}));}
async function quit(){if(!application)return;try{await application.evaluate(({app})=>setTimeout(()=>app.quit(),0));const until=Date.now()+20000;while(alive(pid)&&Date.now()<until)await delay(100);assert.ok(!alive(pid),'App exits with scheduler and classroom cleanup');}finally{if(alive(pid))process.kill(pid,'SIGKILL');if(process.platform==='win32'&&launcher.exitCode===null&&launcher.pid)await exec('taskkill',['/pid',String(launcher.pid),'/T','/F'],{windowsHide:true,timeout:5000}).catch(()=>{});application=undefined;classroom=undefined;}}
async function connect(){if(classroom?.isConnected())return;const [port,path]=(await readFile(join(data,'chrome-profile/DevToolsActivePort'),'utf8')).trim().split(/\r?\n/);classroom=await chromium.connectOverCDP(`ws://127.0.0.1:${port}${path}`);}
const state=()=>window.evaluate(()=>window.attendance.getState());
async function waitState(predicate,timeout=30000){const until=Date.now()+timeout;let latest;while(Date.now()<until){latest=await state();if(predicate(latest))return latest;await delay(100);}throw new Error(`State deadline: ${JSON.stringify({session:latest.session,scheduledRuns:latest.scheduledRuns})}`);}
async function plan(id,weekly=false){const now=await application.evaluate(()=>Date.now());return await window.evaluate(async({id,now,weekly})=>{const planned=Math.ceil((now+5000)/60000)*60000,date=new Date(planned).toISOString(),course=(await window.attendance.getState()).courses[0];await window.attendance.saveSchedule({id,courseId:course.id,enabled:true,localTime:date.slice(11,16),timeZone:'UTC',durationMinutes:1,effectiveFrom:now,recurrence:weekly?{kind:'weekly',weekdays:[new Date(planned).getUTCDay()],startDate:date.slice(0,10)}:{kind:'once',date:date.slice(0,10)}});return {planned,key:`${id}/${date.slice(0,10)}`};},{id,now,weekly});}
async function due(target){await application.evaluate((_electron,target)=>globalThis.__advanceScheduleTo(target),target);}
try{
 await mkdir('.test-artifacts/phase4',{recursive:true});await boot();await window.evaluate(()=>window.attendance.saveSettings({browserMode:'background'}));await window.evaluate(()=>window.attendance.login());await connect();const loginPage=classroom.contexts()[0].pages().find(page=>page.url().startsWith(mock.origin));await loginPage.locator('#sign-in-button').click();await loginPage.locator('.course-title').waitFor();await mock.control({open:true});await window.evaluate(()=>window.attendance.minimizeClassroom());await application.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].hide());const focus=(await native('frontmost')).pid;
 const first=await plan('55555555-5555-4555-8555-555555555555');await due(first.planned+5000);await waitState(s=>s.session?.scheduleKey===first.key&&s.session?.attendance==='confirmed');await mock.control({newQuestion:'single'});await waitState(s=>s.scheduledRuns.some(run=>run.key===first.key&&run.status==='started')&&s.session?.attendance==='confirmed'&&Object.values(s.session?.handled||{}).includes('confirmed'));
 const started=await state();assert.equal(started.session.scheduleKey,first.key);assert.equal(started.session.endsAt,first.planned+60000);assert.equal(started.session.attendance,'confirmed');assert.equal(mock.state.submissions.length,1);assert.equal((await native('frontmost')).pid,focus);
 classroom=undefined;await connect();const firstPid=(await (await classroom.newBrowserCDPSession()).send('SystemInfo.getProcessInfo')).processInfo.find(item=>item.type==='browser').id;chromePids.push(firstPid);assert.equal((await native('visible-windows',String(firstPid))).count,0);
 await window.evaluate(()=>window.attendance.stop());assert.equal((await state()).session.summary.reason,'manual');checks.push('real main-process scheduled start runs headless without focus theft, confirms mock receipts once and preserves the planned end');
 await quit();await boot(first.planned+15000);await delay(5500);const restored=await state();assert.equal(restored.session.id,started.session.id);assert.equal(restored.session.status,'stopped');assert.equal(restored.scheduledRuns.filter(run=>run.key===first.key).length,1);assert.equal(restored.browserConnected,false);assert.equal(mock.state.submissions.length,1);checks.push('real App restart within the same start window does not reopen or resubmit a consumed execution');
 await mock.control({open:true,clearQuestion:true});const second=await plan('66666666-6666-4666-8666-666666666666',true);await due(second.planned+25000);await application.evaluate(({powerMonitor})=>powerMonitor.emit('resume'));await waitState(s=>s.session?.scheduleKey===second.key&&s.session?.attendance==='confirmed',15000);await mock.control({newQuestion:'single'});await waitState(s=>s.session?.scheduleKey===second.key&&s.session?.attendance==='confirmed'&&Object.values(s.session?.handled||{}).includes('confirmed'),15000);assert.equal((await state()).session.endsAt,second.planned+60000);await connect();const secondPid=(await (await classroom.newBrowserCDPSession()).send('SystemInfo.getProcessInfo')).processInfo.find(item=>item.type==='browser').id;chromePids.push(secondPid);await waitState(s=>s.session?.status==='completed',40000);const ended=await state();assert.equal(ended.session.summary.reason,'expired');assert.equal(ended.session.summary.plannedEndsAt,second.planned+60000);assert.equal(mock.state.submissions.length,2);assert.equal(await classroom.contexts()[0].pages().find(page=>page.url().startsWith(mock.origin)).evaluate(()=>window.__attendanceDeadline),0);checks.push('a late scheduled class ends automatically at its original deadline with truthful receipts, summary and zero page gate');
 const cancelled=await plan('77777777-7777-4777-8777-777777777777');await window.evaluate(()=>window.attendance.deleteSchedule('77777777-7777-4777-8777-777777777777'));await due(cancelled.planned+5000);await application.evaluate(({powerMonitor})=>powerMonitor.emit('resume'));await delay(1000);assert.equal((await state()).scheduledRuns.some(run=>run.key===cancelled.key),false);assert.equal((await state()).session.id,ended.session.id);checks.push('a cancelled future task stays cancelled when the resume handler runs; the existing end summary is preserved');
 const missed=await plan('88888888-8888-4888-8888-888888888888');await quit();await boot(missed.planned+660000);await application.evaluate(({powerMonitor})=>powerMonitor.emit('resume'));await waitState(s=>s.scheduledRuns.some(run=>run.key===missed.key&&run.status==='skipped'));assert.equal((await state()).browserConnected,false);assert.equal(mock.state.submissions.length,2);checks.push('an actual App restart and injected resume event record an expired task as missed without opening Chrome or submitting');
 await window.getByRole('button',{name:'定时任务',exact:true}).click();await window.getByRole('region',{name:'定时执行记录',exact:true}).getByText(/已错过本次开始时间/).waitFor();await window.getByRole('region',{name:'定时执行记录',exact:true}).scrollIntoViewIfNeeded();await window.screenshot({path:'.test-artifacts/phase4/scheduler.png'});assert.deepEqual(errors,[]);await quit();for(const id of chromePids)assert.equal(alive(id),false,'dedicated Chrome exits on quit');checks.push('App, scheduler timers and dedicated Chrome clean up on quit');await writeFile('.test-artifacts/phase4/scheduler-report.json',JSON.stringify({checks,syntheticEncryption:synthetic},null,2));console.log(JSON.stringify({checks,syntheticEncryption:synthetic},null,2));
}finally{await quit();for(const id of chromePids)if(alive(id))process.kill(id,'SIGKILL');await mock.close();}
